import PrimeVue from "primevue/config";
import Button from "primevue/button";
import InputText from "primevue/inputtext";
import Toast from "primevue/toast";
import ToastService from "primevue/toastservice";
import Calendar from "primevue/calendar";
import Card from "primevue/card";
import Divider from "primevue/divider";
import InputNumber from "primevue/inputnumber";
import InputMask from "primevue/inputmask";
import Checkbox from "primevue/checkbox";
import Chip from "primevue/chip";
import Breadcrumb from "primevue/breadcrumb";
import Message from "primevue/message";
import Badge from "primevue/badge";
import Dialog from "primevue/dialog";
import ProgressSpinner from "primevue/progressspinner";
import Skeleton from "primevue/skeleton";
import DataTable from "primevue/datatable";
import Column from "primevue/column";
import Dropdown from "primevue/dropdown";
import Stepper from "primevue/stepper";
import StepperPanel from "primevue/stepperpanel";
import TabView from "primevue/tabview";
import TabPanel from "primevue/tabpanel";
import ProgressBar from "primevue/progressbar";
import IconField from "primevue/iconfield";
import InputIcon from "primevue/inputicon";
import RadioButton from 'primevue/radiobutton';
import OverlayPanel from 'primevue/overlaypanel';
import DataView from 'primevue/dataview';
import DataViewLayoutOptions from 'primevue/dataviewlayoutoptions'   // optional
import BlockUI from 'primevue/blockui';
import InlineMessage from 'primevue/inlinemessage';

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(PrimeVue, { ripple: true });
  nuxtApp.vueApp.use(ToastService);
  nuxtApp.vueApp.component("Button", Button);
  nuxtApp.vueApp.component("InputText", InputText);
  nuxtApp.vueApp.component("InputMask", InputMask);
  nuxtApp.vueApp.component("Toast", Toast);
  nuxtApp.vueApp.component("Calendar", Calendar);
  nuxtApp.vueApp.component("Card", Card);
  nuxtApp.vueApp.component("Divider", Divider);
  nuxtApp.vueApp.component("InputNumber", InputNumber);
  nuxtApp.vueApp.component("Checkbox", Checkbox);
  nuxtApp.vueApp.component("Breadcrumb", Breadcrumb);
  nuxtApp.vueApp.component("Chip", Chip);
  nuxtApp.vueApp.component("Message", Message);
  nuxtApp.vueApp.component("Badge", Badge);
  nuxtApp.vueApp.component("Dialog", Dialog);
  nuxtApp.vueApp.component("ProgressSpinner", ProgressSpinner);
  nuxtApp.vueApp.component("Skeleton", Skeleton);
  nuxtApp.vueApp.component("DataTable", DataTable);
  nuxtApp.vueApp.component("Column", Column);
  nuxtApp.vueApp.component("Dropdown", Dropdown);
  nuxtApp.vueApp.component("Stepper", Stepper);
  nuxtApp.vueApp.component("StepperPanel", StepperPanel);
  nuxtApp.vueApp.component("TabView", TabView);
  nuxtApp.vueApp.component("TabPanel", TabPanel);
  nuxtApp.vueApp.component("ProgressBar", ProgressBar);
  nuxtApp.vueApp.component("IconField", IconField);
  nuxtApp.vueApp.component("InputIcon", InputIcon);
  nuxtApp.vueApp.component("RadioButton", RadioButton);
  nuxtApp.vueApp.component("OverlayPanel", OverlayPanel);
  nuxtApp.vueApp.component("DataView", DataView);
  nuxtApp.vueApp.component("DataViewLayoutOptions", DataViewLayoutOptions);
  nuxtApp.vueApp.component("BlockUI", BlockUI);
  nuxtApp.vueApp.component("InlineMessage", InlineMessage);
});
